# .travis.yml

sudo: required
python: '2.7'
dist: xenial
language: python
group: edge

services:
  - docker

env:
  global:
    CACHE_IMAGE: bossjones/docker-build-speed-test
    DOCKER_COMPOSE_VERSION: 1.24.0
    DOCKER_VERSION: 18.09

before_install:
  - sudo apt-get update
  - travis_retry pip install coveralls

  - sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-cache search docker
  - apt-cache madison docker-ce
  - sudo apt-get --allow-downgrades -y -o Dpkg::Options::="--force-confnew" install docker-ce=$(apt-cache madison docker-ce | grep $DOCKER_VERSION | head -1 | awk '{print $3}')

  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version

before_script:
  - docker pull $CACHE_IMAGE:base || true
  - docker pull $CACHE_IMAGE:stage || true

script:
  - docker build
      --target base
      --cache-from $CACHE_IMAGE:base
      --tag $CACHE_IMAGE:base
      --file ./Dockerfile
      "."
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up -d
  - docker-compose -f docker-compose.yml exec web flake8
  - docker-compose -f docker-compose.yml exec web python manage.py test

# after_success:
#   - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
#   - docker push $CACHE_IMAGE:base
#   - docker push $CACHE_IMAGE:stage
