version: '3.7'

services:

  web:
    build:
      context: .
      target: base
      cache_from:
        - bossjones/docker-build-speed-test:base
    image: bossjones/docker-build-speed-test:base
    ports:
      - 5001:5000
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test

